services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tangelo
    ports:
      - '5432:5432'

volumes:
  postgres:
